//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hostel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Room
    {
        public int id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> size { get; set; }
        public string type { get; set; }
        public Nullable<int> price { get; set; }
        public string status { get; set; }
    }
}
